wannglondon/american-townhomes:
  images:
    - https://www.simtropolis.com/objects/screens/monthly_2024_10/One.jpg.a3f46c4df2a583042111a84b37ead649.jpg
    - https://www.simtropolis.com/objects/screens/monthly_2024_10/Two.jpg.437fbb67e3ba9f4fc6cc688fe93bbfb6.jpg
  lastGenerated: 2025-01-13T10:31:15.579Z
  lastModified: 2024-10-15T12:56:56.000Z
  name: WannGLondon's American Rowhomes
  packages:
    - wannglondon/american-townhomes-1
    - wannglondon/american-townhomes-2
    - wannglondon/american-townhomes-3
    - wannglondon/american-townhomes-4
    - wannglondon/american-townhomes-5
    - wannglondon/american-townhomes-6
    - wannglondon/american-townhomes-8
  release: 2025-01-13T10:31:15.579Z
  thumbnail: https://www.simtropolis.com/objects/screens/monthly_2024_10/One.thumb.jpg.08892b0eca7872cec8c609b602f85f64.jpg
  url: https://community.simtropolis.com/files/file/36505-american-rowhomes-pack-1/

wannglondon/ny-buildings:
  images:
    - https://www.simtropolis.com/objects/screens/monthly_2023_09/9.jpg.9d05880f917d262c6b20cd1464348a07.jpg
    - https://www.simtropolis.com/objects/screens/monthly_2023_09/8.jpg.16b9269eb53b5b241febc29b53975d8d.jpg
    - https://www.simtropolis.com/objects/screens/monthly_2023_09/650cd2d8e84c3_Townhomes3.jpg.f196794505d30b26d87c46125700b23b.jpg
    - https://www.simtropolis.com/objects/screens/monthly_2023_09/6.jpg.d533e8a331464378d66ffb7aa8bd7042.jpg
    - https://www.simtropolis.com/objects/screens/monthly_2023_09/1.jpg.fba18eb19c25051ac4e3779cb51d257c.jpg
    - https://www.simtropolis.com/objects/screens/monthly_2023_09/2.jpg.eea76e7eff7bfd7a251b1919928f9539.jpg
    - https://www.simtropolis.com/objects/screens/monthly_2023_09/7.jpg.1deaaa68ccdb6ee1f15a7ad172213b5a.jpg
    - https://www.simtropolis.com/objects/screens/monthly_2023_09/3and4.jpg.e1c85ff7a916e5301a9282520e1dc193.jpg
  lastGenerated: 2025-01-13T10:31:15.545Z
  lastModified: 2023-09-21T23:35:59.000Z
  name: WannGLondon's NY Buildings
  packages:
    - wannglondon/ny-building-1
    - wannglondon/ny-building-2
    - wannglondon/ny-building-3
    - wannglondon/ny-building-4
    - wannglondon/ny-building-6
    - wannglondon/ny-building-7
    - wannglondon/ny-building-8
    - wannglondon/ny-building-9
    - wannglondon/ny-building-10
    - wannglondon/ny-building-11
    - wannglondon/ny-building-12
  release: 2025-01-13T10:31:15.558Z
  thumbnail: https://www.simtropolis.com/objects/screens/monthly_2023_09/9.thumb.jpg.23ef8b3d9bd8cf1860aa6a144781b375.jpg
  url: https://community.simtropolis.com/files/file/35632-new-york-pack-1/
