options:
  - id: rhd
    label: Do you have cars driving on the left?
    section: Transport
    type: boolean
    display: switch
  - id: road-textures
    label: Road textures
    section: Transport
    type: string
    choices:
      - label: US
        value: us
      - label: EU
        value: eu
  - id: culs-de-sacs
    label: Enable cul-de-sac textures
    section: Transport
    type: boolean
    condition:
      nam: true
  - choices:
      - Classic
      - Low
      - Medium
      - High
      - Ultra
    default: Ultra
    id: nam.traffic
    label: NAM - Traffic mode
    section: Transport
    type: string
    condition:
      nam: true
  - choices:
      - value: Maxis_Street_Deciduous_Trees
        label: Maxis, Deciduous
      - value: Maxis_Street_Palm_Trees
        label: Maxis, Palm Trees
      - value: Maxis_Street_Pine_Trees
        label: Maxis, Pines
      - value: CP_Street_Deciduous_Trees
        label: Cycledogg, Deciduous
      - value: CP_Street_Ponderosa_Pines
        label: Cycledogg, Ponderosa Pines
      - value: CP_Street_Shore_Pinyon_Pines
        label: Cycledogg, Shore Pinyon Pines
      - value: PEG_Street_Pines
        label: Pegasus, Pines
    id: sfbt.trees
    label: SFBT trees
    section: SFBT
    type: string
    condition:
      sfbt: true
