7z:
  asset: github/ip7z/7zip
  disabled: true
  exe: 7-Zip/7z.exe
  name: 7-Zip
  repository: https://github.com/ip7z/7zip
  summary: Tool to extract archives
  version: 24.0.6

cicdec:
  asset: github/bioruebe/cicdec
  disabled: true
  exe: cicdec.exe
  name: cicdec
  repository: https://github.com/bioruebe/cicdec
  summary: Tool to extract Clickteam executables
  version: 3.0.1

dgvoodoo:
  asset: simtropolis/36227-dgvoodoo-2-simcity-4-edition
  authors: ulisse-wolf
  description: |-
    **dgVoodoo2 is a set of implementation of old graphics API's for Windows 7 and later versions**

    They are implemented on Direct3D 11/12 and they can use different device types as wrapping output:

    - Hardware rendering at GPU feature level 12.0 (recommended but currently has some issues)
    - Hardware rendering at GPU feature level 11.0 (recommended)
    - Hardware rendering at GPU feature level 10.1 (has a minor limitation for D3D8/9)
    - Hardware rendering at GPU feature level 10.0 (there are some restrictions)
    - Software rendering through Microsoft WARP renderer

    More information at https://dege.freeweb.hu/dgVoodoo2/
  exe: Apps/dgVoodooCpl.exe
  install: DgVoodoo 2 SC4 Version/SimCity 4
  name: DgVoodoo 2 (SimCity 4 Edition)
  repository: https://github.com/dege-diosg/dgVoodoo2
  summary: Compatibility fix for modern hardware
  thumbnail: https://www.simtropolis.com/objects/screens/monthly_2024_04/communityIcon_pznebvf29ih91.thumb.jpg.ff024df162ef710ab91aae67c66745e4.jpg
  url: https://community.simtropolis.com/files/file/36227-dgvoodoo-2-simcity-4-edition/
  version: 2.81.3
  warnings:
    - Some antivirus programs may block the control panel executable. The compatibility fix should work regardless.

reader:
  asset: simtropolis/21343-ilive-reader-093
  authors: ilive
  exe: Reader.exe
  name: iLive Reader
  summary: An advanced modding tool for editing various SC4 game data files, including properties in Exemplar entries
  repository: https://sourceforge.net/projects/ilive-reader/
  thumbnail: https://www.simtropolis.com/objects/screens/monthly_2019_06/Reader-0.9.3-Pic1.thumb.png.c3d3a05c7702be276a86572925e458cb.png
  url: https://community.simtropolis.com/files/file/21343-ilive-reader-093/
  version: 0.9.3

sc4pim:
  asset: sc4evermore/21-sc4pim
  authors: wouanagaine
  exe: bin/SC4PIM.exe
  name: SC4PIM
  summary: SC4PIM, also known as PIM-X or X-Tool, is a better Maxis PIM and LotEditor
  support: https://www.sc4devotion.com/forums/index.php?topic=9279.0
  url: https://www.sc4evermore.com/index.php/downloads/download/29-modding-and-creation-tools/21-sc4pim
  version: 1.0.0
