7z:
  asset: github/ip7z/7zip
  disabled: true
  exe: 7-Zip/7z.exe
  name: 7-Zip
  repository: https://github.com/ip7z/7zip
  summary: Tool to extract archives
  version: 24.0.6

cicdec:
  asset: github/bioruebe/cicdec
  disabled: true
  exe: cicdec.exe
  name: CICDEC
  repository: https://github.com/bioruebe/cicdec
  summary: Tool to extract Clickteam executables
  version: 3.0.1

dgvoodoo:
  asset: simtropolis/36227-dgvoodoo-2-simcity-4-edition
  authors: ulysse-wolf
  exe: Apps/dgVoodooCpl.exe
  install: DgVoodoo 2 SC4 Version/SimCity 4
  name: DgVoodoo 2 (SimCity 4 Edition)
  repository: https://github.com/dege-diosg/dgVoodoo2
  summary: Compatibility fix for modern hardware
  thumbnail: https://www.simtropolis.com/objects/screens/monthly_2024_04/communityIcon_pznebvf29ih91.thumb.jpg.ff024df162ef710ab91aae67c66745e4.jpg
  url: https://community.simtropolis.com/files/file/36227-dgvoodoo-2-simcity-4-edition/
  version: 2.81.3
