7z:
  asset: github/ip7z/7zip
  exe: 7-Zip/7z.exe
  name: 7-Zip
  repository: https://github.com/ip7z/7zip
  summary: A tool to extract archives
  version: 24.0.6

cicdec:
  asset: github/bioruebe/cicdec
  exe: cicdec.exe
  name: CICDEC
  repository: https://github.com/bioruebe/cicdec
  summary: A tool to extract Clickteam executables
  version: 3.0.1
